### ISSUE TITLE
functions lh83pdf and cav76pdf

### ISSUE THREAD

**Issue by maitegouin** [wafo-project/pywafo#37]
Hello,
Thanks for the pywafo version.
Are the functions lh83pdf and cav76pdf available now ?
They are described in the chapter3.py but commented and I don't konw from which module they should belong.
Thanks

**Comment by pbrod** [comment]
Sorry. This is not implemented yet in python.

**Comment by pbrod** [comment]
They are now available in wafo.wavemodels.

**Comment by maitegouin** [comment]
Thanks a lot ! 


De: "Per A. Brodtkorb" <notifications@github.com> 
À: "wafo-project/pywafo" <pywafo@noreply.github.com> 
Cc: "Maite Gouin" <maite.gouin@shom.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 16 Mars 2018 20:15:19 
Objet: Re: [wafo-project/pywafo] functions lh83pdf and cav76pdf (#37) 



They are now available in wafo.wavemodels.
